# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CRDT
tagline:          'в распределенных веб-приложениях'
description:      'Домашнее задание #1 по РИП. Jekyll, GitHub pages.'
assets_url:       '/crdt/assets'

github:
  repo:           https://github.com/nksoff/crdt

collections:
  parts:
    output: false
